# Canonical skill name -> list of aliases (all lowercase)
# Used by both parser (extraction) and insights (overlap computation)
SKILL_ALIASES = {
    "machine learning":     ["machine learning", "ml model", "supervised learning", "unsupervised learning"],
    "deep learning":        ["deep learning", "neural network", "neural networks"],
    "nlp":                  ["nlp", "natural language processing", "text mining", "text analytics"],
    "computer vision":      ["computer vision", "image recognition", "object detection"],
    "data science":         ["data science", "data scientist"],
    "data analysis":        ["data analysis", "data analyst", "data analytics", "eda", "exploratory data analysis"],
    "data visualization":   ["data visualization", "data viz", "tableau", "power bi", "powerbi", "looker", "matplotlib", "seaborn", "plotly"],
    "statistics":           ["statistics", "statistical analysis", "statistical modeling", "hypothesis testing"],
    "feature engineering":  ["feature engineering", "feature selection"],
    "model deployment":     ["model deployment", "mlops", "model serving"],
    "time series":          ["time series", "forecasting", "arima"],
    "llm":                  ["llm", "large language model", "gpt", "bert", "transformers", "huggingface"],
    "a/b testing":          ["a/b testing", "ab testing", "split testing"],
    "python":               ["python"],
    "pandas":               ["pandas"],
    "numpy":                ["numpy"],
    "scikit-learn":         ["scikit-learn", "sklearn", "scikit learn"],
    "tensorflow":           ["tensorflow"],
    "keras":                ["keras"],
    "pytorch":              ["pytorch"],
    "xgboost":              ["xgboost", "lightgbm", "gradient boosting"],
    "scipy":                ["scipy"],
    "jupyter":              ["jupyter"],
    "sql":                  ["sql", "mysql", "postgresql", "postgres", "sqlite"],
    "nosql":                ["mongodb", "cassandra", "dynamodb", "nosql"],
    "spark":                ["spark", "pyspark", "apache spark"],
    "hadoop":               ["hadoop", "hive", "hdfs"],
    "kafka":                ["kafka"],
    "airflow":              ["airflow", "luigi"],
    "aws":                  ["aws", "amazon web services", "sagemaker"],
    "azure":                ["azure", "microsoft azure"],
    "gcp":                  ["gcp", "google cloud", "bigquery", "dataflow"],
    "docker":               ["docker"],
    "kubernetes":           ["kubernetes", "k8s"],
    "git":                  ["git", "github", "gitlab"],
    "linux":                ["linux", "unix", "bash", "shell scripting"],
    "ci/cd":                ["ci/cd", "jenkins", "github actions"],
    "javascript":           ["javascript"],
    "typescript":           ["typescript"],
    "react":                ["react", "reactjs"],
    "vue":                  ["vue", "vuejs"],
    "angular":              ["angular"],
    "java":                 ["java"],
    "scala":                ["scala"],
    "r":                    ["r programming", "rstudio", "tidyverse"],
    "excel":                ["excel", "spreadsheet"],
    "power bi":             ["power bi", "powerbi"],
    "tableau":              ["tableau"],
    "api":                  ["rest api", "restful api", "fastapi", "flask", "django"],
    "devops":               ["devops"],
    "mlflow":               ["mlflow"],
    "reinforcement learning": ["reinforcement learning"],
}
