"""add_total_experience_years_education_job_title

Revision ID: 169817ab64d1
Revises: 
Create Date: 2026-04-06 12:40:30.114016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169817ab64d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # total_experience_years: NOT NULL in model but existing rows have no value.
    # Use server_default='0.0' so SQLite can backfill existing rows safely.
    op.add_column('candidates', sa.Column(
        'total_experience_years', sa.Float(),
        nullable=False, server_default='0.0',
        comment='Total years of professional experience parsed from resume'
    ))
    op.add_column('candidates', sa.Column(
        'education', sa.String(),
        nullable=True,
        comment='Highest education level detected: Bachelor / Master / Phd / B.Tech etc.'
    ))
    op.add_column('candidates', sa.Column(
        'job_title', sa.String(),
        nullable=True,
        comment="Primary job title extracted from resume (e.g. 'Data Scientist', 'Civil Engineer')"
    ))
    op.create_index(op.f('ix_candidates_job_title'), 'candidates', ['job_title'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_job_title'), table_name='candidates')
    op.drop_column('candidates', 'job_title')
    op.drop_column('candidates', 'education')
    op.drop_column('candidates', 'total_experience_years')
    # ### end Alembic commands ###
