"""add_skill_details_json

Revision ID: 702976b10410
Revises: 169817ab64d1
Create Date: 2026-04-06 13:57:07.053871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702976b10410'
down_revision: Union[str, Sequence[str], None] = '169817ab64d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('skill_details', sa.Text(), nullable=True, comment='JSON array of {name, years} objects for per-skill experience. Example: \'[{"name":"Python","years":3},{"name":"SQL","years":5}]\'. HR-editable. Takes precedence over skills field when present.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'skill_details')
    # ### end Alembic commands ###
